let SearchService=(()=>{const o={queryText:null,data:null};return o.template=`<div id="u-search">
  <div class="modal">
    <header class="modal-header" class="clearfix">
      <form id="u-search-modal-form" class="u-search-form" name="uSearchModalForm">
        <input type="text" id="u-search-modal-input" class="u-search-input" />
        <button type="submit" id="u-search-modal-btn-submit" class="u-search-btn-submit">
          <span class="fa-solid fa-search"></span>
        </button>
      </form>
      <a id="u-search-btn-close" class="btn-close"> <span class="fa-solid fa-times"></span> </a>
    </header>
    <main class="modal-body">
      <ul class="modal-results"></ul>
    </main>
  </div>
  <div id="modal-overlay" class="modal-overlay"></div>
</div>
`,o.init=async()=>{var e=document.createElement("div");e.innerHTML+=o.template,document.body.append(e),document.querySelectorAll(".u-search-form").forEach(e=>{e.addEventListener("submit",o.onSubmit,!1)}),document.querySelector("#u-search-modal-input").addEventListener("input",o.onSubmit),document.querySelector("#u-search-btn-close").addEventListener("click",o.close,!1),document.querySelector("#modal-overlay").addEventListener("click",o.close,!1),o.data||(o.data=await o.fetchData())},o.onSubmit=e=>{e.preventDefault();var t=e.target.querySelector(".u-search-input");o.queryText=(t||e.target).value,o.queryText&&o.search()},o.search=async()=>{document.querySelectorAll(".u-search-input").forEach(e=>{e.value=o.queryText}),document.querySelector("#u-search").style.display="block",o.data||(o.data=await o.fetchData());let e="";""===(e=(e+=o.buildResultList(o.data.pages))+o.buildResultList(o.data.posts))&&(e=`<div id="resule-hits-empty"><i class="fa-solid fa-box-open"></i><p>${volantis.GLOBAL_CONFIG.languages.search.hits_empty.replace(/\$\{query}/,o.queryText)}</p></div>`),document.querySelector("#u-search .modal-results").innerHTML=e,document.addEventListener("keydown",function e(t){"Escape"===t.code&&(o.close(),document.removeEventListener("keydown",e))})},o.close=()=>{document.querySelector("#u-search").style.display="none"},o.fetchData=()=>fetch(volantis.GLOBAL_CONFIG.search.dataPath).then(e=>e.text()).then(e=>{return JSON.parse(e)}),o.buildResultList=e=>{let t="";return e.forEach(e=>{e.text&&(e.text=e.text.replace(/12345\d*/g,"")),!e.title&&e.text&&(e.title=e.text.trim().slice(0,15)),o.contentSearch(e)&&(t+=o.buildResult(e.permalink,e.title,e.digest))}),t},o.contentSearch=s=>{let a=s.title.trim().toLowerCase(),r=s.text.trim().toLowerCase(),l=o.queryText.trim().toLowerCase().split(/[-\s]+/),i=!1,n,c=-1,u=-1;return a&&r&&l.forEach((t,e)=>{if(n=a.indexOf(t),c=r.indexOf(t),n<0&&c<0?i=!1:(i=!0,c<0&&(c=0),0===e&&(u=c)),i){r=s.text.trim();let e=0;if(0<=u){t=Math.max(u-40,0),e=0===t?Math.min(200,r.length):Math.min(u+120,r.length);let a=r.substring(t,e);l.forEach(function(e){var t=new RegExp(e,"gi");a=a.replace(t,"<b mark>"+e+"</b>")}),s.digest=a+"......"}else e=Math.min(200,r.length),s.digest=r.trim().substring(0,e)}}),i},o.buildResult=(e,t,a)=>{e=o.getUrlRelativePath(e);let s="";return s=(s+="<li>")+("<a class='result' href='"+e+"?keyword="+o.queryText+"'>")+("<span class='title'>"+t+"</span>"),""!==a&&(s+="<span class='digest'>"+a+"</span>"),s=s+"</a>"+"</li>"},o.getUrlRelativePath=function(e){var e=e.split("//"),t=e[1].indexOf("/");let a=e[1].substring(t);return a=-1!=a.indexOf("?")?a.split("?")[0]:a},{init:()=>{o.init()},setQueryText:e=>{o.queryText=e},search:()=>{o.search()}}})();Object.freeze(SearchService),SearchService.init();